[build]
  command   = "yarn build"

  functions = "out_functions"
  publish   = "out_publish"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "../../tools/plugins/netlify/skip-build"
